### ISSUE TITLE
Will this work on AMD cpu?

### ISSUE THREAD

**Issue by saluransains** [nifanfa/Solution1#2]
Will this work on AMD cpu?

**Comment by nifanfa** [comment]
ofct

**Comment by nifanfa** [comment]
it should work on any x64 architechture based CPU

**Comment by nifanfa** [comment]
if vbe not work you can try uefi branch

**Comment by saluransains** [comment]
Ok, thank you so much!

**Comment by saluransains** [comment]
How to use it?
