### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by saluransains** [nifanfa/Solution1#5]
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/72846692/153336678-e911e9cc-8749-44a2-94de-08d4ec751ec7.png">

**Comment by nifanfa** [comment]
please use the lastest visual studio 2022 and install the latest dev kit of c++

**Comment by nifanfa** [comment]
install the latest desktop development kit for c++

**Comment by saluransains** [comment]
It still does not work

**Comment by reisxd** [comment]
> It still does not work

Try building NativeLib first then running the Kernel

**Comment by saluransains** [comment]
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/72846692/153793344-8c8db563-57c6-43d8-8ed3-8314544a06e2.png">
I can't build NativeLib. it gave me this error

**Comment by saluransains** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/72846692/153793601-f7c06875-7bf8-4513-bb87-345cc668b278.png">
Can't build it because Allocator does not have to Reallocate should I replace it with Allocate

**Comment by nifanfa** [comment]
Clone the latest sourcre.

**Comment by nifanfa** [comment]
let's talk on discord

**Comment by saluransains** [comment]
Ok

**Comment by saluransains** [comment]
Ok this is me: SaluranSains#6313
